// Copyright (C) 1997-2013 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//  Procedure Name:
//      contextPolyToolsObjectMM
//
//  Description:
//      This procedure creates the popup/marking menu
//      for poly object tools. See ModelEdMenu.
//
//  Input Arguments:
//      None
//
//  Return Value:
//      None.


global proc contextPolyToolsObjectMM(){

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kInsertEdgeLoopTool"))
		-annotation (getRunTimeCommandAnnotation("SplitEdgeRingTool"))
		-image "polySplitEdgeRing.png"
		-command "SplitEdgeRingTool"
		-radialPosition "SW"
		;

	menuItem -optionBox true
		-label (uiRes("m_contextPolyToolsObjectMM.kInsertEdgeLoopToolOptions"))
		-annotation (getRunTimeCommandAnnotation("SplitEdgeRingToolOptions"))
		-image "polySplitEdgeRing.png"
		-command "SplitEdgeRingToolOptions"
		-radialPosition "SW"
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kAppendToPolygonTool"))
		-command "setToolTo polyAppendFacetContext ; polyAppendFacetCtx -e -pc `optionVar -q polyKeepFacetsPlanar` polyAppendFacetContext"
		-radialPosition "E"
		-enableCommandRepeat 1
		-image "polyAppendFacet.png"
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kAppendToPolygonToolOptions"))
		-command "setToolTo polyAppendFacetContext ; polyAppendFacetCtx -e -pc `optionVar -q polyKeepFacetsPlanar` polyAppendFacetContext; toolPropertyWindow"
		-optionBox 1
		-radialPosition "E"
		-enableCommandRepeat 1
		;


	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kMergeMenu"))
		-subMenu 1
		-tearOff 0
		-radialPosition "N"
		-allowOptionBoxes 1
		-postMenuCommandOnce 0
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kMergeEdgeTool"))
		-command "MergeEdgeTool"
		// Edited by DRL:
		-radialPosition "NW"
		// -radialPosition "N"
		-enableCommandRepeat 1
		-image "polyMergeEdge.png"
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kMergeEdgeToolOptions"))
		-command "MergeEdgeToolOptions"
		-optionBox 1
		// Edited by DRL:
		-radialPosition "NW"
		// -radialPosition "N"
		-enableCommandRepeat 1
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kPolyBuildMergeVertTool"))
		-annotation (getRunTimeCommandAnnotation("MergeVertexTool"))
		-image "polyMergeVertex.png"
		// Edited by DRL:
		-radialPosition "NE"
		// -radialPosition "S"
		-command "MergeVertexTool"
		;

	menuItem -optionBox true
		-annotation (getRunTimeCommandAnnotation("MergeVertexToolOptions"))
		-image "polyMergeVertex.png"
		// Edited by DRL:
		-radialPosition "NE"
		// -radialPosition "S"
		-command "MergeVertexToolOptions"
		;

	setParent -m ..;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kCutFacesTool"))
		-command "CutPolygon"
		-radialPosition "NE"
		-enableCommandRepeat 1
		-image "polyCut.png"
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kCutFacesToolOptions"))
		-command "CutPolygonOptions"
		-optionBox 1
		-radialPosition "NE"
		-enableCommandRepeat 1
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kSplitMenu"))
		-subMenu 1
		-tearOff 0
		-radialPosition "W"
		-allowOptionBoxes 1
		-postMenuCommandOnce 0
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kSplitPolygonTool"))
		-command "SplitPolygonTool"
		// Edited by DRL:
		-bld 1
		-radialPosition "N"
		// -radialPosition "E"
		-enableCommandRepeat 1
		-image "polySplitFacet.png"
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kSplitPolygonToolOptions"))
		-command "SplitPolygonToolOptions"
		-optionBox 1
		// Edited by DRL:
		-radialPosition "N"
		// -radialPosition "E"
		-enableCommandRepeat 1
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kInteractiveSplitTool"))
		-command "InteractiveSplitTool"
		// Edited by DRL:
		-radialPosition "S"
		// -radialPosition "W"
		-enableCommandRepeat 1
		-image "polySplitFacet.png"
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kInteractiveSplitToolOptions"))
		-command "InteractiveSplitToolOptions"
		-optionBox 1
		// Edited by DRL:
		-radialPosition "S"
		// -radialPosition "W"
		-enableCommandRepeat 1
		;

	setParent -m ..;


	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kSculptGeomTool"))
		-command "SculptGeometryTool"
		-radialPosition "NW"
		-enableCommandRepeat 1
		-image "putty.png"
		;

	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kSculptGeomToolOptions"))
		-command "SculptGeometryToolOptions"
		-optionBox 1
		-radialPosition "NW"
		-enableCommandRepeat 1
		;
				
	menuItem
		-label (uiRes("m_contextPolyToolsObjectMM.kSoftenHardenEdge"))
		-subMenu 1
		-tearOff 0
		-radialPosition "SE"
		-allowOptionBoxes 1
		-postMenuCommandOnce 0
		;

			// Added by DRL: {
			menuItem
				-label ("Lock Normals")
				-command "LockNormals"
				-radialPosition "N"
				-sourceType "mel"
				-itl 1
				-enableCommandRepeat 1
				-image "polyNormalLock.png"
				;
			menuItem
				-label ("Unlock (keep Soft/Hard)")
				-command "from darlog_maya import unlock_normals; reload(unlock_normals); unlock_normals.run()"
				-radialPosition "W"
				-sourceType "python"
				-bld 1
				-enableCommandRepeat 1
				-image "polyNormalUnlock.png"
				;
			menuItem
				-label ("Unlock Normals")
				-command "UnlockNormals"
				-radialPosition "SW"
				-sourceType "mel"
				-itl 1
				-enableCommandRepeat 1
				-image "polyNormalUnlock.png"
				;
			// } End of added
			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kToggleSoftEdgeDisplay"))
				-command "int $g_cond[1]=`polyOptions -q -ae`; if ($g_cond[0]) polyOptions -se; else polyOptions -ae;"
				-radialPosition "S"
				-enableCommandRepeat 1
				-image "commandButton.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kHardenEdge"))
				-command "polyPerformAction \"polySoftEdge -a 0\" e 0"
				-radialPosition "SE"
				-enableCommandRepeat 1
				-image "polySoftEdge.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kSoftenHarden"))
				-command "PolygonSoftenHarden"
				-radialPosition "E"
				-enableCommandRepeat 1
				-image "polySoftEdge.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kSoftenHardenOptions"))
				-command "PolygonSoftenHardenOptions"
				-optionBox 1
				-radialPosition "E"
				-enableCommandRepeat 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kSoftenEdge"))
				-command "polyPerformAction \"polySoftEdge -a 180\" e 0"
				-radialPosition "NE"
				-enableCommandRepeat 1
				-image "polySoftEdge.png"
				;

			setParent -menu ..;

	string $duplicateEdgesLabel, $duplicateEdgesOptions, $duplicateEdgesAnnotation;
	if( !`optionVar -exists polyDuplicateEdgeAsTool` ||
		`optionVar -q polyDuplicateEdgeAsTool` ) {
		$duplicateEdgesLabel = 		(uiRes("m_contextPolyToolsObjectMM.kOffsetEdgeLoopTool"));
		$duplicateEdgesOptions = 	(uiRes("m_contextPolyToolsObjectMM.kOffsetEdgeLoopToolOptions"));
		$duplicateEdgesAnnotation =	(uiRes("m_contextPolyToolsObjectMM.kOffsetEdgeLoopToolAnnot"));
	} else {
		$duplicateEdgesLabel = 		(uiRes("m_contextPolyToolsObjectMM.kOffsetEdgeLoop"));
		$duplicateEdgesOptions =	(uiRes("m_contextPolyToolsObjectMM.kOffsetEdgeLoopOptions"));
		$duplicateEdgesAnnotation =	(uiRes("m_contextPolyToolsObjectMM.kOffsetEdgeLoopAnnot"));
	}

	menuItem
		-label $duplicateEdgesLabel
		-annotation $duplicateEdgesAnnotation
		-image "polyDuplicateEdgeLoop.png"
		-command "DuplicateEdges"
		-dragMenuCommand "performPolyDuplicateEdge 2"
		-dragDoubleClickCommand "DuplicateEdgesOptions"
		//-radialPosition "SE"
		;

	menuItem -optionBox true
		-annotation $duplicateEdgesOptions
		-image "polyDuplicateEdgeLoop.png"
		-command "DuplicateEdgesOptions"
		;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kSmooth"))
				-command "SmoothPolygon"
				-enableCommandRepeat 1
				-image "polySmooth.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kSmoothOptions"))
				-command "performPolySmooth 1"
				-optionBox 1
				-enableCommandRepeat 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kSubdivProxy"))
				-command "SmoothProxy"
				-enableCommandRepeat 1
				-image "polySmoothProxy.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kSubdivProxyOptions"))
				-command "performSmoothProxy 1"
				-optionBox 1
				-enableCommandRepeat 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kCreaseTool"))
				-command "PolyCreaseTool"
				-enableCommandRepeat 1
				-image "polyCrease.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kCreaseToolOptions"))
				-command "PolyCreaseToolOptions"
				-optionBox 1
				-enableCommandRepeat 1
				-image "polyCrease.png"
				;

			menuItem
				-divider 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kProjectCurveOnMesh"))
				-annotation (getRunTimeCommandAnnotation("ProjectCurveOnMesh"))
				-command "ProjectCurveOnMesh";

			menuItem -optionBox true
				-annotation (getRunTimeCommandAnnotation("ProjectCurveOnMeshOptions"))
				-command "ProjectCurveOnMeshOptions";

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kSplitMeshWithProjectedCurve"))
				-annotation (getRunTimeCommandAnnotation("SplitMeshWithProjectedCurve"))
				-command "SplitMeshWithProjectedCurve";

			menuItem -optionBox true
				-annotation (getRunTimeCommandAnnotation("SplitMeshWithProjectedCurveOptions"))
				-command "SplitMeshWithProjectedCurveOptions";

			menuItem
				-divider 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorPolygon"))
				-subMenu 1
				-tearOff 0
				-allowOptionBoxes 1
				-postMenuCommandOnce 0
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorPlusX"))
				-command "polyMirrorFace -ws 1  -direction 0 -mergeMode 1 -ch 1;"
				-enableCommandRepeat 1
				-image "commandButton.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorMinusX"))
				-command "polyMirrorFace -ws 1  -direction 1 -mergeMode 1 -ch 1;"
				-enableCommandRepeat 1
				-image "commandButton.png"
				;


			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorPlusY"))
				-command "polyMirrorFace -ws 1  -direction 2 -mergeMode 1 -ch 1;"
				-enableCommandRepeat 1
				-image "commandButton.png"
				;


			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorMinusY"))
				-command "polyMirrorFace -ws 1  -direction 3 -mergeMode 1 -ch 1;"
				-enableCommandRepeat 1
				-image "commandButton.png"
				;


			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorPlusZ"))
				-command "polyMirrorFace -ws 1  -direction 4 -mergeMode 1 -ch 1;"
				-enableCommandRepeat 1
				-image "commandButton.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorMinusZ"))
				-command "polyMirrorFace -ws 1  -direction 5 -mergeMode 1 -ch 1;"
				-enableCommandRepeat 1
				-image "commandButton.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorOptions"))
				-command "MirrorPolygonGeometryOptions"
				-enableCommandRepeat 1
				;

			menuItem
				-divider 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorCutYZ"))
				-command "polyMirrorCut 1 1 0.001"
				-enableCommandRepeat 1
				-image "polyMirrorCut.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorCutXZ"))
				-command "polyMirrorCut 2 1 0.001"
				-enableCommandRepeat 1
				-image "polyMirrorCut.png"
				;


			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirroCutXY"))
				-command "polyMirrorCut 3 1 0.001"
				-enableCommandRepeat 1
				-image "polyMirrorCut.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kMirrorCutOptions"))
				-command "performPolyMirrorCut 1"
				-enableCommandRepeat 1
				;

			setParent -menu ..;

			//	mapping menu is common to more than objects
			//
			contextPolyToolsMappingMM;

			setParent -menu ..;

			menuItem
				-divider 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kTriangulate"))
				-command "Triangulate"
				-enableCommandRepeat 1
				-image "polyTriangulate.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kQuadrangulate"))
				-command "Quadrangulate"
				-enableCommandRepeat 1
				-image "polyQuad.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kQuadrangulateOptions"))
				-command "performPolyQuadrangulate 1"
				-optionBox 1
				-enableCommandRepeat 1
				;

			menuItem
				-divider 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kSeparate"))
				-command "SeparatePolygon"
				-enableCommandRepeat 1
				-image "polySeparate.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kCombine"))
				-command "CombinePolygons"
				-enableCommandRepeat 1
				-image "polyUnite.png"
				;

			menuItem -optionBox true
				-annotation (getRunTimeCommandAnnotation("CombinePolygonsOptions"))
				-image "polyUnite.png"
				-command "CombinePolygonsOptions"
				;

			menuItem
				-version "2014"
				-label (uiRes("m_contextPolyToolsObjectMM.kBooleans"))
				-subMenu 1
				-tearOff 0
				-allowOptionBoxes 1
				-postMenuCommandOnce 0
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kUnion"))
				-command "polyPerformAction \"polyBoolOp -op 1\" o 0"
				-enableCommandRepeat 1
				-image "polyBooleansUnion.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kDifference"))
				-command "polyPerformAction \"polyBoolOp -op 2\" o 0"
				-enableCommandRepeat 1
				-image "polyBooleansDifference.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kIntersection"))
				-command "polyPerformAction \"polyBoolOp -op 3\" o 0"
				-enableCommandRepeat 1
				-image "polyBooleansIntersection.png"
				;

			setParent -m ..;


			menuItem
				-divider 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kReduce"))
				-command "ReducePolygon"
				-enableCommandRepeat 1
				-image "polyReduce.png"
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kReduceOptions"))
				-command "performPolyReduce 1"
				-optionBox 1
				-enableCommandRepeat 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kCleanup"))
				-command "CleanupPolygonOptions"
				-enableCommandRepeat 1
				-image "polyCleanup.png"
				;

			//setParent -m ..;

			menuItem
				-divider 1
				;

			menuItem
				-label (uiRes("m_contextPolyToolsObjectMM.kPolygonDisplay"))
				-subMenu 1
				-allowOptionBoxes 1
				;

				menuItem
					-label (uiRes("m_contextPolyToolsObjectMM.kToggleBackfaceCulling"))
					-command "int $cond[1]=`polyOptions -q -fb`; if ($cond[0]) polyOptions -bc; else polyOptions -fb;"
					-enableCommandRepeat 1
					-image "commandButton.png"
					-echoCommand 0
					;

				menuItem
					-divider 1
					;

				menuItem
					-label (uiRes("m_contextPolyToolsObjectMM.kToggleBorderEdges"))
					-command "polyOptions -dmb 0 ;polyOptions  -r -db  on"
					-enableCommandRepeat 1
					-image "commandButton.png"
					-echoCommand 0
					;

				menuItem
					-label (uiRes("m_contextPolyToolsObjectMM.kToggleTextureBorderEdges"))
					-command "polyOptions -db 0 ;polyOptions -r -dmb 1"
					-enableCommandRepeat 1
					-image "commandButton.png"
					-echoCommand 0
					;

				menuItem
					-divider 1
					;

				menuItem
					-label (uiRes("m_contextPolyToolsObjectMM.kToggleFaceNormals"))
					-command "polyOptions -r -f -dn on"
					-enableCommandRepeat 1
					-image "commandButton.png"
					-echoCommand 0
					;

				menuItem
					-label (uiRes("m_contextPolyToolsObjectMM.kToggleVertexNormals"))
					-command "polyOptions -r -pt -dn on"
					-enableCommandRepeat 1
					-image "commandButton.png"
					-echoCommand 0
					;

				menuItem
					-divider 1
					;

				menuItem
					-label (uiRes("m_contextPolyToolsObjectMM.kToggleFaceCenters"))
					-command "TogglePolygonFaceCenters"
					-enableCommandRepeat 1
					-image "menuIconDisplay.png"
					-echoCommand 0
					;

				menuItem
					-label (uiRes("m_contextPolyToolsObjectMM.kToggleHiddenTriangles"))
					-command "polyOptions -r -dt 1"
					-enableCommandRepeat 1
					-image "commandButton.png"
					-echoCommand 0
					;

				menuItem
					-label (uiRes("m_contextPolyToolsObjectMM.kToggleVertices"))
					-command "polyOptions -r -displayVertex 1"
					-enableCommandRepeat 1
					-image "menuIconDisplay.png"
					-echoCommand 0
					;

				menuItem
					-divider 1
					;

				menuItem
					-label (uiRes("m_contextPolyToolsObjectMM.kResetPolygonDisplay"))
					-command "polyOptions -activeObjects -ae  -sb 3  -db 0  -dmb 0  -dv 0  -dn 0 -facet  -dc 0  -dt 0  -dw 0  -din 0 0 0 0  -sn 0.4 -bc  -duv 0  -uvt 0  -cs 0  -cm diffuse  -bcv 1"
					-enableCommandRepeat 1
					-image "commandButton.png"
					-echoCommand 0
					;

			setParent -menu ..;

}
